#
# Stickii config file
# 

# Range you wish your users to have (50 is recommended)
range: 50

# Item ID you wish to be the Stickii 'wand' (default is 280)
item: 280

# Set messages for each message event
messages:
  enable: Stickii Enabled.
  disable: Stickii Disabled.
  showrange: true