name: Stickii
author: Kieraan
version: 0.1
main: uk.co.endofinet.plugins.stickii.Stickii
description: >
             Delete any block up to 50 blocks away with a stick!
commands:
  stickii:
    description: Bonk! Block go bye-bye!
    usage: |
            /stickii
    permission: stickii.use